### ISSUE TITLE
Question on handing over the crate to georust org

### ISSUE THREAD

**Issue by JasmineLowen** [lelongg/geo-svg#12]
Hey @lelongg, I really love the crate and I'm kind of sad that it seems to be not maintained anymore. Don't get me wrong, I'm also maintaining some crates and I know it can be a burden. Because of that I developed the mindset that it's good for crates to be owned by an organization. This way you're not responsible all on your own for maintaining it and it's also future proof for the community.

Let me know what you think of this! I can try to orchestrate all the organizational stuff for you as much as possible if you're up for it.

**Comment by lelongg** [comment]
Hello, no problem for handing over control to georust, not much time to invest on this crate anymore so feel free to contact the org.

**Comment by JasmineLowen** [comment]
I contacted the org on discord and they agreed on the plan. I'll volunteer to be the maintainer for the future of the crate.

I think the most important thing left todo is to add the `georust` org as an owner of the crate on crates.io. Not sure how that works exactly. Because of that I propose you just add me `RobWalt` as an owner and I'll figure it out for you and take on the rest.

**Comment by JasmineLowen** [comment]
@lelongg Sorry for the ping. I don't want to stress you out and at the same time I just want to make sure it isn't lost.

**Comment by lelongg** [comment]
Ok, no worries, I've just sent you the invite on crates.io. I should have made some background check on you since supply chain attacks are a thing, but I don't even know what proof you could provide me...

**Comment by JasmineLowen** [comment]
Thanks for the fast reply. I make sure to add the geo org as fast as possible and let you know here.

**Comment by JasmineLowen** [comment]
The publisher team of the georust org has been added to the crates admins. Thanks again and I won't bother you anymore 😅
